import { APP_CONFIG } from "@/config/app";
import { MYINFO_CONNECTOR_CONFIG } from "@/config/myinfo";

export const SHOWN_CONFIG = {
  SCOPE: APP_CONFIG.DEMO_APP_SCOPES,
  DEMO_APP_CLIENT_PRIVATE_SIGNING_KEY:
    MYINFO_CONNECTOR_CONFIG.CLIENT_PRIVATE_SIGNING_KEY,
  DEMO_APP_CLIENT_PRIVATE_ENCRYPTION_KEY:
    MYINFO_CONNECTOR_CONFIG.CLIENT_PRIVATE_ENCRYPTION_KEY,
  DEMO_APP_CLIENT_ID: APP_CONFIG.DEMO_APP_CLIENT_ID,
  DEMO_APP_PURPOSE_ID: APP_CONFIG.DEMO_APP_PURPOSE_ID,
  DEMO_APP_CALLBACK_URL: APP_CONFIG.DEMO_APP_CALLBACK_URL,
  GRANT_TYPE: "authorization_code",
};
